import Head from 'next/head'

export default function About() {
  return (
    <>
      <Head>
          <title>About page</title>
          <meta name="description" content="Generated by create about next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>About page</p>
      </main>
    </>
  )
}
