import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
          <title>Welcome to MERN Next app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello Mamun</h1>
      </main>
    </>
  )
}
