import Head from 'next/head'
import Link from 'next/link'

export default function Blog() {
  return (
    <>
      <Head>
          <title>Blog page</title>
          <meta name="description" content="Generated by create blog next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Blog page <br/><Link href="/blog/01">Show More..</Link></p>
      </main>
    </>
  )
}
